### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group05#6]
very cool choice of dataset!

Mechanics:
- Readme file does not do a proper introduction to your repo and project, a bit more details are required
- if HTML is given, it should be viewable ( through GitHub pages). I marked  .md document and the header there needs to be edited as it looks a bit messy, and 2/3 of the document did not appear, neither in html

your report:
- great introduction and data description, very informative!

I guess you ran out of time to finish the rest of the assignment:/ I am really looking forward to see what you will demonstrate in your next step!

Other issues you need to address:
- .Rproj should not be in the repo, it is your private document that you do not share ( so when you do commit from R studio, make sure you don't include the Rproj changes)

**Comment by firasm** [comment]
@sciclic and @jacobgerlofs : Yulia will also have a look at your [milestone1.1](https://github.com/STAT547-UBC-2019-20/group05/tree/milestone_1.1) for additional feedback.

**Comment by yuliaUU** [comment]
Had a look at your milestone 1 again: Overall, nicely done! Just a couple of things I noticed:
*Exploring the dataset*
Something wrong with `![](milestone-01_files/figure-html/basic demographics1-1.png) And just to view this as a percentage of our data frame...` link as it is not displaying the picture. same issue onwards.

as it is a group project I would not use such sentences as " I'm curious to see how..", I would replace "I" with "we".

graphs that show satisfaction level the x-axes, the scale overlaps each other (3 and 4). I understand that you posted an issue about it, so I know you are trying to solve this issue.

I would suggest exploring the relationship between two continuous variables ( so that you can do linear regressions or smth like that)
