### ISSUE TITLE
Deploying app to Heroku

### ISSUE THREAD

**Issue by iciarfernandez** [STAT547-UBC-2019-20/group05#61]
Hi @yuliaUU,

I was just going through the guidebook again to remember how we deployed an app to Heroku in class previously, but I'm a bit confused as to how to do this with our repo. My "app" is now on heroku.com and I got to the "deploy branch" step, but it's giving me errors. I guess my questions are:

1. Where do the required files (Dockerfile, heroku.yml, app.json, init.R, and apt-packages) need to be located within our repo? I first had them in the "scripts" folder but it gave me the error "cannot find a heroku.yml file" on Heroku.com, so I changed them to the root repo folder but I'm not sure that's how I'm supposed to approach that issue?

2. I am now getting this error, which I don't understand:

=== Fetching app code
=!= There were problems parsing your heroku.yml. We've detected the following issues:
"build" must validate one and only one schema (oneOf). Found none valid
build.docker in body is a forbidden property
build.web in body is a forbidden property

Thank you!!

**Comment by yuliaUU** [comment]
1) all 5 files and app should be in one main folder, and Heroku should be connected to that folder specifically:
![image](https://user-images.githubusercontent.com/54612866/78510739-668da480-774c-11ea-9314-48ffd9839f5f.png)

2) not sure about the error, but did you updated init.R and other files to match your app?

**Comment by yuliaUU** [comment]
also, did you forked the repo and put it outside your project ( e.g. somewhere om desktop for instance) and then do the steps described in the guide/?

**Comment by iciarfernandez** [comment]
I did fork the repo and put it in a temporary folder I created on my desktop, and I updated my init.R to include all packages that my app.R uses. I now also moved my app.R to the main repo folder like you said above (it was under 'scripts' before), but still getting this error:

=== Fetching app code.
=!= There were problems parsing your heroku.yml. We've detected the following issues:
"build" must validate one and only one schema (oneOf). Found none valid
build.docker in body is a forbidden property
build.web in body is a forbidden property

**Comment by yuliaUU** [comment]
did you check the heroku.yaml is all good and indented properly
also, the Dockfile all the app name match?

**Comment by iciarfernandez** [comment]
I think so? I'm not sure of how to check that.

My heroku.yml looks like this:
```
build:
  docker:
  web: Dockerfile
```

And my Dockerfile looks like this:

```
FROM plotly/heroku-docker-r:3.6.2_heroku18

# on build, copy application files
COPY . /app/
  
  # for installing additional dependencies etc.
  RUN if [ -f '/app/onbuild' ]; then bash /app/onbuild; fi; 

# look for /app/apt-packages and if it exists, install the packages contained
RUN if [ -f '/app/apt-packages' ]; then apt-get update -q && cat apt-packages | xargs apt-get -qy install && rm -rf /var/lib/apt/lists/*; fi;              

# look for /app/init.R and if it exists, execute it
RUN if [ -f '/app/init.R' ]; then /usr/bin/R --no-init-file --no-save --quiet --slave -f /app/init.R; fi; 

# here app.R needs to match the name of the file which contains your app              
CMD cd /app && /usr/bin/R --no-save -f /app/app.R
```

My app script is called app.R

**Comment by yuliaUU** [comment]
how your app is called?

**Comment by iciarfernandez** [comment]
On Heroku.com I named it phd-satisfaction, is that what you mean?

**Comment by yuliaUU** [comment]
no, the actual script to run app: is it app.R or smth else?

**Comment by iciarfernandez** [comment]
It's app.R

**Comment by yuliaUU** [comment]
everything looks fine then in those apps.
what about init.R? what did you put inside?

**Comment by yuliaUU** [comment]
and after you moved the app, didi you commit and push the changes?

**Comment by iciarfernandez** [comment]
These are the contents of init.R,

```
# R script to run author supplied code, typically used to install additional R packages
# contains placeholders which are inserted by the compile script
# NOTE: this script is executed in the chroot context; check paths!

r <- getOption('repos')
r['CRAN'] <- 'http://cloud.r-project.org'
options(repos=r)

# ======================================================================

# packages go here
install.packages('remotes')

remotes::install_github('plotly/dashR', upgrade=TRUE)
install.packages('tidyverse')
install.packages('plotly')
install.packages('gapminder')
install.packages('ggsci')
install.packages('ggplot2')
```

**Comment by iciarfernandez** [comment]
yeah I did commit and push the changes, the app is on the main root repo folder both on GitHub and in my local clone in the temporary folder I created in my computer.

**Comment by yuliaUU** [comment]
let me try and redo your app, and see whether I encounter the same issues, ok?

**Comment by iciarfernandez** [comment]
sounds good, thank you so much!

**Comment by yuliaUU** [comment]
I was an easy to fix;
first 
1. your .yml file is not indented properly: web should be indented more: that was a source of error
```
build:
  docker:
    web: Dockerfile
```
2. you init.R loads wrong packages: you don't even yous gapminder, and your app.r have way more libraries than you list there

**Comment by iciarfernandez** [comment]
**Thank you so much!** The app seemed to be deploying successfully, but the app doesn't actually display. In regards to your init.R comment, do the dash libraries also have to be loaded? I think that's what I'm confused about

**Comment by yuliaUU** [comment]
@sciclic yes, all the libraries listed in README to your repo have to be installed. 
dash is installed with this code:
```
# packages go here
install.packages('remotes')

remotes::install_github('plotly/dashR', upgrade=TRUE)
```
you dont need to load any other dash related libraries

**Comment by iciarfernandez** [comment]
I see, thank you! I thought it only needed to be the libraries that were loaded in the app.R script. I'm trying now once I've updated it and I will let you know if it works. Thanks for all the help @yuliaUU ! :)

**Comment by iciarfernandez** [comment]
Hi again @yuliaUU, so I added all the libraries in our README to the init.R and deployed the app, the message on Heroku.com says that it was deployed successfully, but this is what shows up when I try to actually open the app 

![Screenshot (133)](https://user-images.githubusercontent.com/55170602/78597388-4b7d6c00-7802-11ea-930c-6ca650c84b8f.png)

**Comment by yuliaUU** [comment]
if you type in terminal, `heroku logs -- tail`, what will you get?

**Comment by iciarfernandez** [comment]
![Screenshot (135)](https://user-images.githubusercontent.com/55170602/78597836-102f6d00-7803-11ea-9e7d-5d8b739a8d37.png)

This is the output of `heroku logs --tail` in terminal

**Comment by yuliaUU** [comment]
can you give me a link to updated files, i will have a look

**Comment by iciarfernandez** [comment]
yes, thank you!

- [init.R](https://github.com/STAT547-UBC-2019-20/group05/blob/master/init.R)

- [heroku.yml](https://github.com/STAT547-UBC-2019-20/group05/blob/master/heroku.yml)

**Comment by yuliaUU** [comment]
this is what I found [H10 error](https://dev.to/lawrence_eagles/causes-of-heroku-h10-app-crashed-error-and-how-to-solve-them-3jnl). @firasm , maybe you saw it already and can help with it?

**Comment by iciarfernandez** [comment]
thank you @yuliaUU, not too sure of how to fix that so we'll wait for @firasm to reply.!

**Comment by yuliaUU** [comment]
@sciclic can you try again?
i changed indenting of [.yml](https://github.com/STAT547-UBC-2019-20/group05/blob/master/heroku.yml). can you run using this one?

**Comment by iciarfernandez** [comment]
Running it right now! Thank you. Will let you know once it's finished

**Comment by iciarfernandez** [comment]
Now it's giving me a different error. Would it show up for you with the link phd-satisfaction.herokuapp.com?

![Screenshot (136)](https://user-images.githubusercontent.com/55170602/78603478-11659780-780d-11ea-8e3b-b6a0de485fd5.png)

**Comment by iciarfernandez** [comment]
I actually tried reloading a couple times, and now it gives me the same "application error" as before @yuliaUU

**Comment by iciarfernandez** [comment]
Hey just a small (unsuccessful) update that I deleted the app from Heroku, cloned the repo into a temp folder from scratch again, and repeated the whole process but still not working. I thought maybe that would be the easiest way, but no luck :(

**Comment by yuliaUU** [comment]
@firasm , we cant seem to pinpoint the issue

**Comment by yuliaUU** [comment]
Can you try to reduce your datasets by half and run it?

**Comment by iciarfernandez** [comment]
What do you mean by reduce the datasets by half? Right now I am attempting to deploy from terminal instead, based on this https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#getting-started-existing-app

Thanks for all the help @yuliaUU, sorry we've had so many issues

**Comment by yuliaUU** [comment]
make the data twice less; for example instead 4000 entries, do 1000. I was just wondering whether it is size related issue or not

**Comment by iciarfernandez** [comment]
Oh I see. Right now Jacob is trying to deploy it from his end to see if it somehow works for him, otherwise we'll try that! We did reduce the dataset for the app.R script (created a new dataframe called survey_dash.csv with less columns than the original), but I suppose it could still be a size issue

**Comment by firasm** [comment]
When I try to run it (with debug=TRUE), I get an error,

```
Invalid argument `value` passed into Slider with ID "ageslider".
Expected `number`.
Was supplied type `string`.
Value provided: "1"
```

<img width="1367" alt="Screen Shot 2020-04-06 at 9 42 52 PM" src="https://user-images.githubusercontent.com/2507459/78630967-e5b7d100-784f-11ea-88e2-9489df1928e7.png">

I think your problem is Line 62:

```
make_plot2 <- function(ageslider = "1"){
```

the "1" shouldn't be a string, but a value.

**Comment by firasm** [comment]
There's also a second bug:

your app$run_server needs to be:

```
app$run_server(host = "0.0.0.0", port = Sys.getenv('PORT', 8050))
```

when it's deployed to heroku. Otherwise you will get errors like:

"App boot timeout"

**Comment by firasm** [comment]
Ok your app now deploys for me: https://test-app-squirrels.herokuapp.com

The last comment I made is most likely the error (I'm not sure what's going with your make_plot2 but it seems to work both ways)

**Comment by jacobgerlofs** [comment]
@firasm @yuliaUU ,

Thanks for all your help, it seems to be running correctly now! The app$run_server change did the trick, although the make_plot function did not work correctly for me and deployment failed when passing 1 as a value :information_desk_person: Nonetheless, it's working now when passed as a string. Thanks :grin:
